vaadin.launch-browser=true
spring.application.name=crm

server.port=8080
server.servlet.session.timeout=8h

spring.datasource.url=jdbc:postgresql://localhost:5432/quad_crm
spring.datasource.username=anggara
spring.datasource.password=TahuTelor24

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
