-- Create country and region master tables.
-- Requires pgcrypto/gen_random_uuid(), already enabled by the initial migration.

CREATE TABLE countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,

    iso_code_2 VARCHAR(2) NOT NULL UNIQUE,
    iso_code_3 VARCHAR(3) UNIQUE,
    name VARCHAR(100) NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,

    country_id BIGINT NOT NULL,
    parent_id BIGINT,

    code VARCHAR(13) NOT NULL,
    name VARCHAR(100) NOT NULL,

    region_level SMALLINT NOT NULL,
    region_type VARCHAR(20) NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_regions_country
        FOREIGN KEY (country_id)
        REFERENCES countries(id),

    CONSTRAINT fk_regions_parent
        FOREIGN KEY (parent_id)
        REFERENCES regions(id),

    CONSTRAINT uq_regions_country_code
        UNIQUE (country_id, code),

    CONSTRAINT chk_regions_level
        CHECK (region_level IN (1, 2)),

    CONSTRAINT chk_regions_type
        CHECK (region_type IN ('PROVINCE', 'REGENCY', 'CITY'))
);

CREATE INDEX idx_regions_country_level_name
    ON regions(country_id, region_level, name);

CREATE INDEX idx_regions_parent_name
    ON regions(parent_id, name);
