CREATE TABLE option_groups (
                               code VARCHAR(50) PRIMARY KEY,
                               name VARCHAR(100) NOT NULL,
                               description TEXT,
                               is_active BOOLEAN NOT NULL DEFAULT TRUE,
                               is_system BOOLEAN NOT NULL DEFAULT FALSE,

                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE option_values (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,

                               group_code VARCHAR(50) NOT NULL,

                               code VARCHAR(50) NOT NULL,
                               name VARCHAR(100) NOT NULL,
                               description TEXT,

                               sort_order INT NOT NULL DEFAULT 0,
                               color VARCHAR(50),
                               icon VARCHAR(100),

                               is_active BOOLEAN NOT NULL DEFAULT TRUE,
                               is_system BOOLEAN NOT NULL DEFAULT FALSE,
                               is_final BOOLEAN NOT NULL DEFAULT FALSE,

                               is_won BOOLEAN NOT NULL DEFAULT FALSE,
                               is_lost BOOLEAN NOT NULL DEFAULT FALSE,

                               metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_option_values_group
                                   FOREIGN KEY (group_code) REFERENCES option_groups(code),

                               CONSTRAINT uq_option_values_group_code
                                   UNIQUE (group_code, code),

                               CONSTRAINT chk_option_values_won_lost
                                   CHECK (NOT (is_won = TRUE AND is_lost = TRUE)),

                               CONSTRAINT chk_option_values_metadata_object
                                   CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX idx_option_values_group_code ON option_values(group_code);
CREATE INDEX idx_option_values_active_sort ON option_values(group_code, is_active, sort_order);

INSERT INTO option_groups (code, name, description, is_system) VALUES
                                                                   ('LEAD_STATUS', 'Lead Status', 'Status list for lead pipeline', TRUE),
                                                                   ('OPPORTUNITY_STATUS', 'Opportunity Status', 'Status list for opportunity pipeline', TRUE),
                                                                   ('ACTIVITY_TYPE', 'Activity Type', 'Type list for CRM activities', TRUE);

INSERT INTO option_values (
    group_code, code, name, sort_order, color, icon, is_system, is_final, metadata
) VALUES
      ('LEAD_STATUS', 'NEW', 'New', 1, 'primary', 'PLUS', TRUE, FALSE,
       '{"allowConvertToOpportunity": false, "showInPipeline": true}'::jsonb),

      ('LEAD_STATUS', 'FOLLOW_UP_VALIDATE', 'Follow Up / Validate', 2, 'warning', 'PHONE', TRUE, FALSE,
       '{"allowConvertToOpportunity": false, "showInPipeline": true}'::jsonb),

      ('LEAD_STATUS', 'VALID', 'Valid', 3, 'success', 'CHECK', TRUE, TRUE,
       '{"allowConvertToOpportunity": true, "showInPipeline": true}'::jsonb),

      ('LEAD_STATUS', 'INVALID', 'Invalid', 4, 'error', 'CLOSE', TRUE, TRUE,
       '{"allowConvertToOpportunity": false, "showInPipeline": true, "requireInvalidReason": true}'::jsonb);

INSERT INTO option_values (
    group_code, code, name, sort_order, color, icon, is_system, is_final, is_won, is_lost, metadata
) VALUES
      ('OPPORTUNITY_STATUS', 'PRODUCT_SOLUTIONING', 'Product / Solutioning', 1, 'primary', 'TOOLS', TRUE, FALSE, FALSE, FALSE,
       '{"showInPipeline": true, "allowEditAmount": true, "requireLostReason": false}'::jsonb),

      ('OPPORTUNITY_STATUS', 'TENDER', 'Tender', 2, 'contrast', 'FILE_TEXT', TRUE, FALSE, FALSE, FALSE,
       '{"showInPipeline": true, "allowEditAmount": true, "requireLostReason": false}'::jsonb),

      ('OPPORTUNITY_STATUS', 'NEGOTIATION', 'Negotiation', 3, 'warning', 'COMMENTS', TRUE, FALSE, FALSE, FALSE,
       '{"showInPipeline": true, "allowEditAmount": true, "requireLostReason": false}'::jsonb),

      ('OPPORTUNITY_STATUS', 'WON', 'Won', 4, 'success', 'CHECK', TRUE, TRUE, TRUE, FALSE,
       '{"showInPipeline": true, "allowEditAmount": false, "requireLostReason": false}'::jsonb),

      ('OPPORTUNITY_STATUS', 'LOST', 'Lost', 5, 'error', 'CLOSE', TRUE, TRUE, FALSE, TRUE,
       '{"showInPipeline": true, "allowEditAmount": false, "requireLostReason": true}'::jsonb);

INSERT INTO option_values (
    group_code, code, name, sort_order, color, icon, is_system, metadata
) VALUES
      ('ACTIVITY_TYPE', 'NOTE', 'Note', 1, 'contrast', 'NOTE', TRUE,
       '{"manualInput": true, "showDueDate": false, "showCompletedButton": false}'::jsonb),

      ('ACTIVITY_TYPE', 'CALL', 'Call', 2, 'primary', 'PHONE', TRUE,
       '{"manualInput": true, "showDueDate": false, "showCompletedButton": false}'::jsonb),

      ('ACTIVITY_TYPE', 'MEETING', 'Meeting', 3, 'contrast', 'CALENDAR', TRUE,
       '{"manualInput": true, "showDueDate": true, "showCompletedButton": false}'::jsonb),

      ('ACTIVITY_TYPE', 'EMAIL', 'Email', 4, 'success', 'ENVELOPE', TRUE,
       '{"manualInput": true, "showDueDate": false, "showCompletedButton": false}'::jsonb),

      ('ACTIVITY_TYPE', 'WHATSAPP', 'WhatsApp', 5, 'success', 'CHAT', TRUE,
       '{"manualInput": true, "showDueDate": false, "showCompletedButton": false}'::jsonb),

      ('ACTIVITY_TYPE', 'TASK', 'Task', 6, 'warning', 'CHECK_SQUARE', TRUE,
       '{"manualInput": true, "showDueDate": true, "showCompletedButton": true}'::jsonb),

      ('ACTIVITY_TYPE', 'STATUS_CHANGE', 'Status Change', 7, 'contrast', 'EXCHANGE', TRUE,
       '{"manualInput": false, "showDueDate": false, "showCompletedButton": false}'::jsonb),

      ('ACTIVITY_TYPE', 'CREATED', 'Created', 8, 'contrast', 'PLUS', TRUE,
       '{"manualInput": false, "showDueDate": false, "showCompletedButton": false}'::jsonb),

      ('ACTIVITY_TYPE', 'CONVERTED', 'Converted', 9, 'primary', 'ARROW_RIGHT', TRUE,
       '{"manualInput": false, "showDueDate": false, "showCompletedButton": false}'::jsonb),

      ('ACTIVITY_TYPE', 'ASSIGNED', 'Assigned', 10, 'warning', 'USER', TRUE,
       '{"manualInput": false, "showDueDate": false, "showCompletedButton": false}'::jsonb);