CREATE TABLE companies (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,

                           name VARCHAR(200) NOT NULL,
                           industry VARCHAR(150),
                           website VARCHAR(200),
                           email VARCHAR(150),
                           phone VARCHAR(50),

                           address TEXT,
                           city VARCHAR(100),
                           province VARCHAR(100),
                           country VARCHAR(100),

                           notes TEXT,

                           created_by BIGINT,
                           updated_by BIGINT,

                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT fk_companies_created_by
                               FOREIGN KEY (created_by) REFERENCES users(id),

                           CONSTRAINT fk_companies_updated_by
                               FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE INDEX idx_companies_name ON companies(name);
CREATE INDEX idx_companies_email ON companies(email);
CREATE INDEX idx_companies_phone ON companies(phone);

CREATE TABLE persons (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,

                         company_id BIGINT,

                         full_name VARCHAR(150) NOT NULL,
                         job_title VARCHAR(150),
                         email VARCHAR(150),
                         phone VARCHAR(50),
                         whatsapp VARCHAR(50),

                         notes TEXT,

                         created_by BIGINT,
                         updated_by BIGINT,

                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT fk_persons_company
                             FOREIGN KEY (company_id) REFERENCES companies(id),

                         CONSTRAINT fk_persons_created_by
                             FOREIGN KEY (created_by) REFERENCES users(id),

                         CONSTRAINT fk_persons_updated_by
                             FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE INDEX idx_persons_company_id ON persons(company_id);
CREATE INDEX idx_persons_full_name ON persons(full_name);
CREATE INDEX idx_persons_email ON persons(email);
CREATE INDEX idx_persons_phone ON persons(phone);