CREATE TABLE leads (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,

                       title VARCHAR(200) NOT NULL,

                       company_id BIGINT,
                       person_id BIGINT,

                       raw_company_name VARCHAR(200),
                       raw_person_name VARCHAR(150),
                       raw_email VARCHAR(150),
                       raw_phone VARCHAR(50),

                       source VARCHAR(100),

                       status_group_code VARCHAR(50) NOT NULL DEFAULT 'LEAD_STATUS',
                       status_code VARCHAR(50) NOT NULL DEFAULT 'NEW',

                       assigned_to BIGINT,

                       description TEXT,
                       notes TEXT,

                       validated_at TIMESTAMP,
                       invalid_reason TEXT,

                       created_by BIGINT,
                       updated_by BIGINT,

                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT fk_leads_company
                           FOREIGN KEY (company_id) REFERENCES companies(id),

                       CONSTRAINT fk_leads_person
                           FOREIGN KEY (person_id) REFERENCES persons(id),

                       CONSTRAINT fk_leads_status
                           FOREIGN KEY (status_group_code, status_code)
                               REFERENCES option_values(group_code, code),

                       CONSTRAINT fk_leads_assigned_to
                           FOREIGN KEY (assigned_to) REFERENCES users(id),

                       CONSTRAINT fk_leads_created_by
                           FOREIGN KEY (created_by) REFERENCES users(id),

                       CONSTRAINT fk_leads_updated_by
                           FOREIGN KEY (updated_by) REFERENCES users(id),

                       CONSTRAINT chk_leads_status_group
                           CHECK (status_group_code = 'LEAD_STATUS')
);

CREATE INDEX idx_leads_status ON leads(status_group_code, status_code);
CREATE INDEX idx_leads_assigned_to ON leads(assigned_to);
CREATE INDEX idx_leads_company_id ON leads(company_id);
CREATE INDEX idx_leads_person_id ON leads(person_id);
CREATE INDEX idx_leads_created_at ON leads(created_at);
CREATE INDEX idx_leads_raw_company_name ON leads(raw_company_name);
CREATE INDEX idx_leads_raw_person_name ON leads(raw_person_name);