CREATE TABLE opportunities (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,

                               title VARCHAR(200) NOT NULL,

                               lead_id BIGINT,
                               company_id BIGINT,
                               person_id BIGINT,

                               status_group_code VARCHAR(50) NOT NULL DEFAULT 'OPPORTUNITY_STATUS',
                               status_code VARCHAR(50) NOT NULL DEFAULT 'PRODUCT_SOLUTIONING',

                               estimated_amount NUMERIC(18, 2),
                               probability INT,
                               expected_close_date DATE,

                               assigned_to BIGINT,

                               description TEXT,
                               notes TEXT,

                               won_at TIMESTAMP,
                               lost_at TIMESTAMP,
                               lost_reason TEXT,

                               created_by BIGINT,
                               updated_by BIGINT,

                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_opportunities_lead
                                   FOREIGN KEY (lead_id) REFERENCES leads(id),

                               CONSTRAINT fk_opportunities_company
                                   FOREIGN KEY (company_id) REFERENCES companies(id),

                               CONSTRAINT fk_opportunities_person
                                   FOREIGN KEY (person_id) REFERENCES persons(id),

                               CONSTRAINT fk_opportunities_status
                                   FOREIGN KEY (status_group_code, status_code)
                                       REFERENCES option_values(group_code, code),

                               CONSTRAINT fk_opportunities_assigned_to
                                   FOREIGN KEY (assigned_to) REFERENCES users(id),

                               CONSTRAINT fk_opportunities_created_by
                                   FOREIGN KEY (created_by) REFERENCES users(id),

                               CONSTRAINT fk_opportunities_updated_by
                                   FOREIGN KEY (updated_by) REFERENCES users(id),

                               CONSTRAINT chk_opportunities_status_group
                                   CHECK (status_group_code = 'OPPORTUNITY_STATUS'),

                               CONSTRAINT chk_opportunities_probability
                                   CHECK (probability IS NULL OR probability BETWEEN 0 AND 100)
);

CREATE INDEX idx_opportunities_status ON opportunities(status_group_code, status_code);
CREATE INDEX idx_opportunities_assigned_to ON opportunities(assigned_to);
CREATE INDEX idx_opportunities_lead_id ON opportunities(lead_id);
CREATE INDEX idx_opportunities_company_id ON opportunities(company_id);
CREATE INDEX idx_opportunities_person_id ON opportunities(person_id);
CREATE INDEX idx_opportunities_expected_close_date ON opportunities(expected_close_date);
CREATE INDEX idx_opportunities_created_at ON opportunities(created_at);