CREATE TABLE activities (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,

                            type_group_code VARCHAR(50) NOT NULL DEFAULT 'ACTIVITY_TYPE',
                            type_code VARCHAR(50) NOT NULL DEFAULT 'NOTE',

                            subject VARCHAR(200),
                            description TEXT,

                            lead_id BIGINT,
                            opportunity_id BIGINT,
                            company_id BIGINT,
                            person_id BIGINT,

                            activity_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            due_date TIMESTAMP,
                            completed_at TIMESTAMP,

                            metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

                            created_by BIGINT,

                            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                            CONSTRAINT fk_activities_type
                                FOREIGN KEY (type_group_code, type_code)
                                    REFERENCES option_values(group_code, code),

                            CONSTRAINT fk_activities_lead
                                FOREIGN KEY (lead_id) REFERENCES leads(id),

                            CONSTRAINT fk_activities_opportunity
                                FOREIGN KEY (opportunity_id) REFERENCES opportunities(id),

                            CONSTRAINT fk_activities_company
                                FOREIGN KEY (company_id) REFERENCES companies(id),

                            CONSTRAINT fk_activities_person
                                FOREIGN KEY (person_id) REFERENCES persons(id),

                            CONSTRAINT fk_activities_created_by
                                FOREIGN KEY (created_by) REFERENCES users(id),

                            CONSTRAINT chk_activities_type_group
                                CHECK (type_group_code = 'ACTIVITY_TYPE'),

                            CONSTRAINT chk_activities_target
                                CHECK (
                                    lead_id IS NOT NULL
                                        OR opportunity_id IS NOT NULL
                                        OR company_id IS NOT NULL
                                        OR person_id IS NOT NULL
                                    ),

                            CONSTRAINT chk_activities_metadata_object
                                CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX idx_activities_type ON activities(type_group_code, type_code);
CREATE INDEX idx_activities_lead_id ON activities(lead_id);
CREATE INDEX idx_activities_opportunity_id ON activities(opportunity_id);
CREATE INDEX idx_activities_company_id ON activities(company_id);
CREATE INDEX idx_activities_person_id ON activities(person_id);
CREATE INDEX idx_activities_created_by ON activities(created_by);
CREATE INDEX idx_activities_activity_date ON activities(activity_date);
CREATE INDEX idx_activities_due_date ON activities(due_date);

CREATE TABLE attachments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,

                             original_filename VARCHAR(255) NOT NULL,
                             stored_filename VARCHAR(255) NOT NULL,
                             file_path TEXT NOT NULL,
                             mime_type VARCHAR(100),
                             file_size BIGINT,

                             lead_id BIGINT,
                             opportunity_id BIGINT,
                             company_id BIGINT,
                             person_id BIGINT,

                             uploaded_by BIGINT,

                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             CONSTRAINT fk_attachments_lead
                                 FOREIGN KEY (lead_id) REFERENCES leads(id),

                             CONSTRAINT fk_attachments_opportunity
                                 FOREIGN KEY (opportunity_id) REFERENCES opportunities(id),

                             CONSTRAINT fk_attachments_company
                                 FOREIGN KEY (company_id) REFERENCES companies(id),

                             CONSTRAINT fk_attachments_person
                                 FOREIGN KEY (person_id) REFERENCES persons(id),

                             CONSTRAINT fk_attachments_uploaded_by
                                 FOREIGN KEY (uploaded_by) REFERENCES users(id),

                             CONSTRAINT chk_attachments_target
                                 CHECK (
                                     lead_id IS NOT NULL
                                         OR opportunity_id IS NOT NULL
                                         OR company_id IS NOT NULL
                                         OR person_id IS NOT NULL
                                     )
);

CREATE INDEX idx_attachments_lead_id ON attachments(lead_id);
CREATE INDEX idx_attachments_opportunity_id ON attachments(opportunity_id);
CREATE INDEX idx_attachments_company_id ON attachments(company_id);
CREATE INDEX idx_attachments_person_id ON attachments(person_id);
CREATE INDEX idx_attachments_uploaded_by ON attachments(uploaded_by);