INSERT INTO option_groups (code, name, description, is_active, is_system)
VALUES ('PRODUCT_TYPE', 'Product Type', 'Product and item category list', TRUE, TRUE)
ON CONFLICT (code) DO NOTHING;

INSERT INTO option_values (
    group_code, code, name, sort_order, color, icon, is_active, is_system, metadata
) VALUES
      ('PRODUCT_TYPE', 'HARDWARE', 'Hardware', 1, 'contrast', 'CUBE', TRUE, TRUE, '{}'::jsonb),
      ('PRODUCT_TYPE', 'SOFTWARE', 'Software', 2, 'primary', 'CODE', TRUE, TRUE, '{}'::jsonb),
      ('PRODUCT_TYPE', 'SERVICE', 'Service', 3, 'success', 'TOOLS', TRUE, TRUE, '{}'::jsonb)
ON CONFLICT (group_code, code) DO NOTHING;

CREATE TABLE lead_items (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,

                            lead_id BIGINT NOT NULL,

                            product_type_group_code VARCHAR(50) NOT NULL DEFAULT 'PRODUCT_TYPE',
                            product_type_code VARCHAR(50) NOT NULL,

                            item_name VARCHAR(200) NOT NULL,
                            description TEXT,
                            quantity INT NOT NULL,
                            estimated_unit_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
                            estimated_total NUMERIC(18, 2) NOT NULL DEFAULT 0,
                            notes TEXT,
                            sort_order INT NOT NULL DEFAULT 0,

                            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                            CONSTRAINT fk_lead_items_lead
                                FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,

                            CONSTRAINT fk_lead_items_product_type
                                FOREIGN KEY (product_type_group_code, product_type_code)
                                    REFERENCES option_values(group_code, code),

                            CONSTRAINT chk_lead_items_product_type_group
                                CHECK (product_type_group_code = 'PRODUCT_TYPE'),

                            CONSTRAINT chk_lead_items_quantity
                                CHECK (quantity > 0),

                            CONSTRAINT chk_lead_items_prices
                                CHECK (estimated_unit_price >= 0 AND estimated_total >= 0)
);

CREATE INDEX idx_lead_items_lead_id ON lead_items(lead_id);
CREATE INDEX idx_lead_items_product_type ON lead_items(product_type_group_code, product_type_code);
CREATE INDEX idx_lead_items_sort_order ON lead_items(lead_id, sort_order);

CREATE TABLE opportunity_items (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,

                                   opportunity_id BIGINT NOT NULL,

                                   product_type_group_code VARCHAR(50) NOT NULL DEFAULT 'PRODUCT_TYPE',
                                   product_type_code VARCHAR(50) NOT NULL,

                                   item_name VARCHAR(200) NOT NULL,
                                   description TEXT,
                                   quantity INT NOT NULL,
                                   unit_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
                                   total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
                                   notes TEXT,
                                   sort_order INT NOT NULL DEFAULT 0,

                                   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                   CONSTRAINT fk_opportunity_items_opportunity
                                       FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE,

                                   CONSTRAINT fk_opportunity_items_product_type
                                       FOREIGN KEY (product_type_group_code, product_type_code)
                                           REFERENCES option_values(group_code, code),

                                   CONSTRAINT chk_opportunity_items_product_type_group
                                       CHECK (product_type_group_code = 'PRODUCT_TYPE'),

                                   CONSTRAINT chk_opportunity_items_quantity
                                       CHECK (quantity > 0),

                                   CONSTRAINT chk_opportunity_items_prices
                                       CHECK (unit_price >= 0 AND total_amount >= 0)
);

CREATE INDEX idx_opportunity_items_opportunity_id ON opportunity_items(opportunity_id);
CREATE INDEX idx_opportunity_items_product_type ON opportunity_items(product_type_group_code, product_type_code);
CREATE INDEX idx_opportunity_items_sort_order ON opportunity_items(opportunity_id, sort_order);
